### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by TheKnarf** [TheKnarf/codemodr#4]
The project needs a logo.

The project name is a simplification of `codemod runner`. While I don't have much concrete ideas for how the logo should look I think it should have something to do with code and somehow modifying it.

I'd also like for the `r` in `codemodr` to somehow be accentuated, maybe it could be in cursive, bold or another colour.

**Comment by munadikieh** [comment]
Hi @TheKnarf. 
I see that you want a new logo for your project. If you wish, I can do it for you without any problem .I will present some ideas that would improve your project. 

Munadi Kiehl

**Comment by TheKnarf** [comment]
That would be great @munadikieh !

**Comment by munadikieh** [comment]
Hi @TheKnarf 
This is my proposal for codemoder logo.
![Artboard 2](https://user-images.githubusercontent.com/41304326/61704315-a3a43900-ad6d-11e9-95cb-534898f89106.jpg)
If you have any revision, please tell me :)

Munadi Kiehl

**Comment by TheKnarf** [comment]
I do like the curly-bracket together with the R! Thats pretty clever!

The color scheme is also great!

However the C feels a bit unreadable, I end up reading it as `odemod R`.
So it might be better to just use a normal C with the same font, at least I'd like to see what that looks like.

I also think I prefer the right side where we keep the baseline the same.
Could you mock up what it would look like if whe had a normal C, the curly-bracket R, and a fixed baseline like the right examples?

**Comment by munadikieh** [comment]
Thanks @TheKnarf for your feedback. I have revision logo use normal font and curly-bracket together with the R, also the same baseline.
![Artboard 3](https://user-images.githubusercontent.com/41304326/61762478-4b684800-adfc-11e9-816c-ac32e9fc2a86.jpg)

Please give your feedback :)

**Comment by TheKnarf** [comment]
I think that looks rather nice :)

How would it look if the `{R` part was in cursive / italic?

**Comment by munadikieh** [comment]
Hi @TheKnarf, Sorry for late reply, I have included bold, italic and italic bold
![Artboard 4](https://user-images.githubusercontent.com/41304326/61988819-de99bb80-b050-11e9-94fa-7f4365dbd157.jpg)

If you have any revision, please tell me :)

**Comment by TheKnarf** [comment]
Number 1 and 3 looks the best. I think we'll go with 3 :)

**Comment by munadikieh** [comment]
Thank @TheKnarf for make a choice, I think the logo Number 3 look good and suitable with the project. I have created PR #6 and Original File in [GDrive](https://drive.google.com/drive/folders/1ErhK-RUenOU7e0i5bn52Z8w7yd2nGVeq?usp=sharing). Have a nice Day :)

Best Regard,
Munadi Kiehl

**Comment by munadikieh** [comment]
Hi Knarf..
Would you describe detail of your project codemodR. I want to use for my
portofolio.

Best regard,
Munadi Kiehl
